# Site settings
course_name: Deep Learning
course_description: "Deep Learning has lately become the driving force behind numerous high-performing AI/ML products deployed in
real-world across diverse disciplines. Tech gaints such as Google, Microsoft, Facebook, Amazon, etc. have strongly been employing 
the Deep Learning workforce in the past few years for developing a wide range of applications in Computer Vision, Natural Processing, etc.
Hence, it has become one of the most sough after learning courses in recent times. In this predominantly theory course, we will discuss the various
building blocks required to realize the Deep Learning based solutions."
course_semester: "Jan-May 2023"

baseurl: "/dl" # the subpath of your site, e.g. /blog/
url: "http://krmopuri.github.io/" # the base hostname & protocol for your site

schoolname: "Dept. of AI, IITH"
schoolurl: "https://ai.iith.ac.in/"
#twitter_username: username 

address: |
    Department of Artificial Intelligence
    IIT Hyderabad, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
